import type { NextPage } from "next";
import Head from "next/head";
import { Hero, Vision, Work, Started, Faq } from "../views/landing";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>tidal.financial</title>
        <meta name="description" content="Generated by Next.js" />
      </Head>
      <main>
        <Hero />
        <Vision />
        <Work />
        <Started />
        <Faq />
      </main>
    </>
  );
};

export default Home;
